require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '94741026371',
    MODE: (process.env.MODE || 'public').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia01QYXdsZVNOSEJKMHowMmVmczJaRkptR3BCRXJVL3l2Nlk3WGwwVzMyZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZW11VDhwSlh6WHRLWkxqNUd2ZFpvMVNtMlNLeFlnSXN1S3JUZnBNZ256UT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1SnFsWHJiRzJXaUEwdG1vUlBJMzUvRFYvcjJ2a2ZrUHdNbHR0WmEvYjNjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJzODBCZGE4SjRlVkxVdk04NDJRQStoY1Q5SkYzS0tzVjR0bUdsOUh0SUdvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFGV21CeWFaa2RNMGppUGRvbEpZL2lkYTFXc0txM0VHdjBiRFo1VGlmM3c9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1MTzhLejkxKzlobXpzMDRtQnkxU3lMMXNRR3ZKUVdXdUJBTVZXMFlBaDg9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicUpUUFlFMHdCZ24vRi9jczR6MWZTTDNMcFhkc0NLendvbVVDNW5wVGhFZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0ZBR3cwbWtqZFNmaGM3RW84ck1iWGhadHQ3RW5mNjVwMUR4OE16VmlVcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjI4K1ZqeXk4UktHUytoUUVqYlErMzVKU1Y5SFNOZ0FzSSt5WGxITTI1Q1E4eHYrU0J2SDBCZlJIWHZCWnFWZkh1Q3EzNmU1aDNnZzdOUXdxOFBLNEF3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjIxLCJhZHZTZWNyZXRLZXkiOiJHRHVpYm1URHNsTFAyQlVEL1V0NFJ5QTdRME9LSFZFNE5qRE05T0lVaXVBPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxMDI2MzcxQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkQ2OENFNkJCMzRGNDkwRjNEQTc4RDgwNUQxMkE1ODBEIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQ2NjA5MTR9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxMDI2MzcxQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjQ4OTA5MDI1Q0MyQUNCQTk4QTUwRDZBNEQzMDQzNzRCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQ2NjA5MjJ9LHsia2V5Ijp7InJlbW90ZUppZCI6Ijk0NzQxMDI2MzcxQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkU2NUUyNkJCMzc3ODJFOEI2RUZENUE0OEE0MDIzN0IxIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQ2NjA5MjN9XSwibmV4dFByZUtleUlkIjo2MSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjYxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlNKMkg2QUYyIiwibWUiOnsiaWQiOiI5NDc0MTAyNjM3MTo4N0BzLndoYXRzYXBwLm5ldCIsImxpZCI6IjEzMDM5OTU2OTIzMjAxNTo4N0BsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0tLaWlJQURFSjZBMk1RR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImJZSzJ3eVkwUExtaS95bGZmTkJFYTN3Tld2aGFIZjVZUUU4cU4yaUwxaDg9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImpEM3M4TWk4SEdMMmJ0Tnp3cXRwSW96eVFhSDhDUDAvc1hEdWswbDVZOVNJOE9BaExWbzlmS05ydnUwREpZOEpiWXJMWXh6aURjQm5hM2xZdjM1MUJ3PT0iLCJkZXZpY2VTaWduYXR1cmUiOiJQcENJUTdleGNRSXlNSkM1eWkvWVlRd1l2a0lOUTVMWks0U0pyRXd3My9OaXpPNGtwTnJMUnhNZytENGhvYXlDdnFmczY4eVJUblVKS3lRdU5NN2RDQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0NzQxMDI2MzcxOjg3QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlcyQ3RzTW1ORHk1b3Y4cFgzelFSR3Q4RFZyNFdoMytXRUJQS2pkb2k5WWYifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNBZ0lEUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1NDY2MDkwOCwibGFzdFByb3BIYXNoIjoiMUs0aEg0IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFLM0IifQ==',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
